import re
#!/usr/bin/env python3
"""
registry.py — the vault's registry: every note and meta-note, generated from the files themselves.

The tracker is derived, never kept by hand: a number a person must keep true is a claim nothing
keeps true. It leaves itself out of everything it counts — an index that reads its own output is
a mirror, not an instrument. It holds facts only, no verdicts, so the check can read it without
reading itself. Regenerating it from an unchanged vault gives the same bytes; `cerebrum.py check`
goes RED when the note on disk and a fresh regeneration disagree.
"""
import os
from collections import defaultdict, Counter
import cerebrum as C
import checks as K

MIN_LINES = 20       # below this many substantial lines, containment says nothing about a note

def _lines(text):
    """The substantial lines of a note's body (four words or more) — what containment is measured on."""
    return {l.strip() for l in K._body(text).splitlines() if len(l.split()) >= 4}

def _frontmatter(text):
    if not text.startswith("---\n"):
        return {}
    fm = {}
    for line in text[4:text.find("\n---", 4)].splitlines():
        if ":" in line and not line.startswith((" ", "-")):
            k, _, val = line.partition(":")
            fm[k.strip()] = val.strip()
    return fm

def pin_lines(cfg):
    """Each frozen root, why it is frozen, and where the code pins it — as the code says now."""
    rows = []
    for f in cfg.get("frozen", []):
        found = []
        for path, literal in f.get("pins", []):
            try:
                with open(os.path.expanduser(path), encoding="utf-8", errors="replace") as fh:
                    nums = [str(i) for i, l in enumerate(fh.read().splitlines(), 1) if literal in l]
                found.append(f"{path}:{','.join(nums[:4]) if nums else 'NOT FOUND'}")
            except OSError:
                found.append(f"{path}: MISSING")
        rows.append((f["root"], f.get("why", ""), found))
    return rows

def cell(s):
    return str(s).replace("|", "\\|")

def build(root, cfg):
    v = K.Vault(root, cfg)
    reg = cfg.get("registry", "")
    title = os.path.splitext(os.path.basename(reg))[0] or "Registry"
    meta = lambda p: any(p.startswith(d + "/") for d in cfg.get("meta_dirs", []))
    sensitive = set(v.accepted.get("sensitive", []))            # never opened, never counted
    notes = [p for p in v.movable if K.MD(p) and p != reg and p not in sensitive]
    text = {p: v.text(p) for p in notes}

    by_name = defaultdict(list)
    for p in notes:
        by_name[K.base(p)].append(p)
    out_n, in_n = Counter(), Counter()
    for p in notes:
        for m in C.WIKI.finditer(C._strip_code(text[p])):
            t = m.group(1).split("|")[0].split("#")[0].strip().lower()
            if not t:
                continue
            out_n[p] += 1
            hits = by_name.get(t[:-3] if t.endswith(".md") else t, [])
            if len(hits) == 1 and hits[0] != p:
                in_n[hits[0]] += 1

    by_hash = defaultdict(list)
    for p in v.movable:
        if p != reg and p not in sensitive and os.path.getsize(os.path.join(root, p)) > 0:
            by_hash[v.hash(p)].append(p)
    twins = {p: [q for q in ps if q != p] for ps in by_hash.values() if len(ps) > 1 for p in ps}

    # containment between notes that are not plain copies (copies are listed once, as copies)
    L = {p: _lines(text[p]) for p in notes if not meta(p) and p not in twins}
    contained = {}
    for p, lp in L.items():
        if len(lp) < MIN_LINES:
            continue
        best = max(((len(lp & lq) / len(lp), q) for q, lq in L.items() if q != p and lq), default=(0.0, None))
        if best[0] >= 0.5:
            contained[p] = best
    # "A is inside B" and "B mostly overlaps A" are one fact seen from both sides: keep the first
    for p, (f, q) in list(contained.items()):
        if f < 0.99 and q in contained and contained[q][1] == p and contained[q][0] >= 0.99:
            del contained[p]

    done = sorted(p for p in notes if meta(p) and re.search(r"\b(EXECUTED|RUN|APPLIED)\b", _frontmatter(text[p]).get("status", "").upper()))
    homes = Counter(p.split("/")[0] for p in notes)
    groups = sorted({tuple(sorted([p] + qs)) for p, qs in twins.items()})
    accepted = set(v.accepted.get("duplicates", []))

    md = [f"---\nrole: generated by `cerebrum.py registry` — do not edit by hand; regenerate instead\n---\n\n"
          f"# {title}\n\n"
          "Every note and meta-note in the vault, generated from the files themselves. It leaves itself out "
          "of everything it counts and holds facts only; regenerated from an unchanged vault it comes out "
          "byte for byte the same, and `cerebrum.py check` goes RED when it doesn't.\n",
          "## Counts", "",
          f"- notes: **{len(notes)}** — " + " · ".join(f"{h} {homes.get(h, 0)}" for h in v.para),
          f"- inbox depth: **{homes.get(v.para[0], 0)}**",
          f"- meta-notes: **{sum(1 for p in notes if meta(p))}**",
          f"- identical copies: **{len(groups)}** group(s) (accepted: {sum(1 for g in groups if set(g) <= accepted)})",
          f"- frozen folders: **{len(cfg.get('frozen', []))}** (their files are live and not counted here)", ""]

    md += ["## Meta-notes — the system's notes about itself", "", "| note | words | changed |", "|---|---|---|"]
    for p in sorted(x for x in notes if meta(x)):
        mt = os.path.getmtime(os.path.join(root, p))
        md.append(f"| `{cell(p)}` | {len(text[p].split()):,} | {C.datetime.fromtimestamp(mt):%Y-%m-%d} |")

    md += ["", "## The frozen register — as the code says today", "", "| folder | why | pinned by (file:line) |", "|---|---|---|"]
    for r, why, found in pin_lines(cfg):
        md.append(f"| `{cell(r)}` | {cell(why)} | {cell('; '.join(found) or '—')} |")

    md += ["", "## Proposals — nothing moves or goes without the keeper", "",
           "**Identical copies** — keep one of each when you decide:"]
    md += [f"- " + " = ".join(f"`{cell(x)}`" for x in g) + (" (accepted)" if set(g) <= accepted else "")
           for g in groups] or ["- none"]
    # a live note wholly inside an ARCHIVED one is not redundant: the archive keeps its fuller original
    arch = lambda p: p.split("/")[0] == v.para[-1]
    orig = sorted(p for p, (f, q) in contained.items() if f >= 0.99 and not arch(p) and arch(q))
    rem = sorted(p for p, (f, q) in contained.items() if f >= 0.99 and p not in orig)
    cand = sorted(p for p, (f, q) in contained.items() if f < 0.99)
    md += ["", "**Fully contained in another note** — removable when you say:"]
    md += [f"- `{cell(p)}` — {contained[p][0]:.0%} inside `{cell(contained[p][1])}`" for p in rem] or ["- none"]
    md += ["", "**Originals kept in the archive** — a live note wholly inside its fuller original; nothing to remove:"]
    md += [f"- `{cell(contained[p][1])}` holds all of `{cell(p)}`" for p in orig] or ["- none"]
    md += ["", "**Overlapping** — merge candidates:"]
    md += [f"- `{cell(p)}` — {contained[p][0]:.0%} inside `{cell(contained[p][1])}`" for p in cand] or ["- none"]
    md += ["", "**Carried-out plans** — done; archive when you like:"]
    md += [f"- `{cell(p)}`" for p in done] or ["- none"]

    md += ["", "## Every note", "", "| note | words | links out | links in | copy or container |", "|---|---|---|---|---|"]
    for p in sorted(notes):
        rel = (f"copy of `{cell(twins[p][0])}`" if p in twins else
               f"{contained[p][0]:.0%} in `{cell(contained[p][1])}`" if p in contained else "")
        md.append(f"| `{cell(p)}` | {len(text[p].split()):,} | {out_n[p]} | {in_n[p]} | {rel} |")
    return "\n".join(md) + "\n"

def write(root, cfg):
    path = os.path.join(root, cfg["registry"])
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(build(root, cfg))
    return path

def fresh(root, cfg):
    """True when the registry on disk equals a fresh regeneration."""
    p = os.path.join(root, cfg.get("registry", ""))
    if not cfg.get("registry") or not os.path.isfile(p):
        return False
    with open(p, encoding="utf-8") as fh:
        return fh.read() == build(root, cfg)
